require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/event_hists", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # EventHist. As you add validations to EventHist, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    #skip("Add a hash of attributes valid for your model")
    {
      event_id: 1,
      user_id: 1,
      sign_in: 'True',
      point_recv: 5
    }
  }

  let(:invalid_attributes) {
    #skip("Add a hash of attributes invalid for your model")
    {
      event_id: nil,
      user_id: nil,
      sign_in: nil,
      point_recv: nil
    }
  }

  describe "GET /index" do
    it "renders a successful response" do
      EventHist.create! valid_attributes
      get event_hists_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      event_hist = EventHist.create! valid_attributes
      get event_hist_url(event_hist)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_event_hist_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      event_hist = EventHist.create! valid_attributes
      get edit_event_hist_url(event_hist)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new EventHist" do
        expect {
          post event_hists_url, params: { event_hist: valid_attributes }
        }.to change(EventHist, :count).by(1)
      end

      it "redirects to the created event_hist" do
        post event_hists_url, params: { event_hist: valid_attributes }
        expect(response).to redirect_to(event_hist_url(EventHist.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new EventHist" do
        expect {
          post event_hists_url, params: { event_hist: invalid_attributes }
        }.to change(EventHist, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post event_hists_url, params: { event_hist: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested event_hist" do
        event_hist = EventHist.create! valid_attributes
        patch event_hist_url(event_hist), params: { event_hist: new_attributes }
        event_hist.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the event_hist" do
        event_hist = EventHist.create! valid_attributes
        patch event_hist_url(event_hist), params: { event_hist: new_attributes }
        event_hist.reload
        expect(response).to redirect_to(event_hist_url(event_hist))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        event_hist = EventHist.create! valid_attributes
        patch event_hist_url(event_hist), params: { event_hist: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested event_hist" do
      event_hist = EventHist.create! valid_attributes
      expect {
        delete event_hist_url(event_hist)
      }.to change(EventHist, :count).by(-1)
    end

    it "redirects to the event_hists list" do
      event_hist = EventHist.create! valid_attributes
      delete event_hist_url(event_hist)
      expect(response).to redirect_to(event_hists_url)
    end
  end
end
